### ISSUE TITLE
Command to Display all available functionalities

### ISSUE THREAD

**Issue by 0x15F9** [Abdur-rahmaanJ/honeybot#110]
add a command to display all the functionalities of the bot.
eg: .help should list the commands followed by a brief description

**Comment by Abdur-rahmaanJ** [comment]
or the link to a page

**Comment by RiceAbove** [comment]
I’m actually working on this right now. Will get it done soon 👍🏼

**Comment by Abdur-rahmaanJ** [comment]
@RiceAbove leave it for first timers ^^_

**Comment by RiceAbove** [comment]
👍🏼

**Comment by edumello** [comment]
Can I work on this?

**Comment by Abdur-rahmaanJ** [comment]
@edumello yes

**Comment by edumello** [comment]
Since actually there is no way to automatically get a brief description of all plugins installed, I've thought in two options:

-  Hard code all commands on a plugin Help

- Add variables "plugin_name", "description", "commands" on all Plugins (maybe a superclass?) and read it from a plugin Help

Which option should I follow?

**Comment by Abdur-rahmaanJ** [comment]
@edumello there is, we have a script to generate plugins info . md, enhance it to show commands as well and ... on .help show the github link of that file

**Comment by edumello** [comment]
I've opened a PR #117

**Comment by 0x15F9** [comment]
> Since actually there is no way to automatically get a brief description of all plugins installed, I've thought in two options:
> 
> * Hard code all commands on a plugin Help
> * Add variables "plugin_name", "description", "commands" on all Plugins (maybe a superclass?) and read it from a plugin Help
> 
> Which option should I follow?

Maybe a .md file would help here. Use the file to store information about each functions (the name, command, description, author)

**Comment by GlennToms** [comment]
I think we should go with a Abstract Class (SuperClass) with Name, Description, Run, Alias and a Alternate Language.  We can easily do a Plugins_V2 folder and slowly migrate the code over.   This will allow the bot to query the plugins that are enabled and we can disable them by name...  This will be very helpful on the GUI side.   
Also maybe we should be passing in the Command_Prefix so if we or the user wants to change it to anything else like a **'/'** they can.
Lastly we should pass in the logging function so we use it  from the plugins.

**Comment by AngeloGiacco** [comment]
agree but command_prefix is tricky because some symbols like "/" are reserved for IRC commands

**Comment by Abdur-rahmaanJ** [comment]
@AngeloGiacco actually after you get msgs, / in messages matters not
@GlennToms open two issues for those points
@0x15F9 issue resolved since long
