### ISSUE TITLE
uptime plugin

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/honeybot#125]
.uptime

returns the time the bot has been running

**Comment by ispite** [comment]
Hello, I would like to contribute to your project, but I'm new

**Comment by Abdur-rahmaanJ** [comment]
hey no worry, read the README, brwose plugins directory and join the discord server, we'll help you!

**Comment by Abdur-rahmaanJ** [comment]
@ispite

**Comment by nickw409** [comment]
Added uptime plugin
