### ISSUE TITLE
Monopoly GUI

### ISSUE THREAD

**Issue by AngeloGiacco** [Abdur-rahmaanJ/honeybot#130]
It seems that the monopoly plugin is working well but, unlike the hangman plugin and the possible poker plugin, having it just text based obviously doesnt work so great. A monopoly GUI would be great if anyone has the time and energy. Not sure whether it would fit into the honeybot GUI or be a separate window.

**Comment by Macr0Nerd** [comment]
@Abdur-rahmaanJ I think we should consider whether this is a viable feature, considering the people playing may not actually have it installed but may be accessing it on another server
