### ISSUE TITLE
add plugin dev documentation

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/honeybot#14]

**Comment by dpanek26** [comment]
Hello! I would very much be interested in tackling this.

**Comment by Abdur-rahmaanJ** [comment]
see how plugins are made, each plugin has the same structure. write a mini tutorial. see the test file to see what each method returns

**Comment by Abdur-rahmaanJ** [comment]
@dpanek26  added in README due to increasing contributors. excuses.
