### ISSUE TITLE
Add lol/abbreviation decoder plugin

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/honeybot#155]
.def lol

returns

lots of love

**Comment by chibitofu** [comment]
Hi I'd like to take this issue.

**Comment by Abdur-rahmaanJ** [comment]
@chibitofu any question, join our discord server!

**Comment by chibitofu** [comment]
I think this can be closed. It's resolved by https://github.com/Abdur-rahmaanJ/honeybot/pull/157

**Comment by AngeloGiacco** [comment]
shouldn't the solution be more like a web scraping tool to find the definition, i think the current solution is a little clunky and not scalable

**Comment by Abdur-rahmaanJ** [comment]
@AngeloGiacco That's for another new comer issue
