### ISSUE TITLE
expand .def to use Urban dictionary 

### ISSUE THREAD

**Issue by AngeloGiacco** [Abdur-rahmaanJ/honeybot#158]
.def should return the meaning of a phrase from urban dictionary. I suggest you use bs4 and requests to scrape the website.

**Comment by duttasourav000** [comment]
Hi @AngeloGiacco , I am a newcomer and would like to contribute. Can I work on this issue? Where do I start?

**Comment by Abdur-rahmaanJ** [comment]
@duttasourav000 

- join our discord server
- see the plugin [here](https://github.com/Abdur-rahmaanJ/honeybot/blob/master/honeybot/plugins/abbreviation.py) modify it
- scrape some website to get all definition or just use a dictionary

**Comment by duttasourav000** [comment]
Thanks! I'll work on it and send a PR.
