### ISSUE TITLE
complete setup.py

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/honeybot#159]
setup.py nearly empty. complete it.

**Comment by Dizzerin** [comment]
Hi, I'm new to this and would like to make my first contribution to an open source project.  What does this issue entail?  What is setup.py supposed to do here or where can I find this out?  Thanks so much!

**Comment by Abdur-rahmaanJ** [comment]
@Dizzerin see the setup.py file. search how a setup.py file should be. fill in accordingly. join our discord server for questions!

**Comment by PoseidonSigmaX** [comment]
@Abdur-rahmaanJ I'm in a similar position to @Dizzerin . Where can I find an invite to your Discord server?

**Comment by Abdur-rahmaanJ** [comment]
@PoseidonSigmaX see Readme under Discord section

**Comment by PoseidonSigmaX** [comment]
Cool, found it, thanks!
