### ISSUE TITLE
add setup.py

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/honeybot#16]

**Comment by hugolesta** [comment]
Hello Abdur,

I made a new setup.py for honeybot.

Could you please tell me how can I show you my code? I can't create a new branch in your project.

Thank you!

**Comment by Abdur-rahmaanJ** [comment]
just click create new file on honeybot project (my project), then click propose new file. complete for pull request. that's easier for a begining than forking, branching and PR

**Comment by vysor** [comment]
Done, just created file and made a PR.
