### ISSUE TITLE
add a hangman / guess the word plugin

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/honeybot#21]
no need to draw the man but update user of right or wrong guess and chances remaining

**Comment by justinwalker4179** [comment]
I'd love to try and make this plugin. Currently I'm trying to run main.py and getting a bunch of weird syntax errors that are making me think I'm missing something. This is the first one, but there are so many of this same kind of error, I must be not catching something.


On line 144:
```python
print(f"\033[0;36mListfrom is {listfrom}\033[0;0m")
```
SyntaxError: invalid syntax

**Comment by Abdur-rahmaanJ** [comment]
@justinwalker4179 that uses 3.7 just comment them out

**Comment by Macr0Nerd** [comment]
@justinwalker4179 @Abdur-rahmaanJ that was my bad. I left those in for easy debugging and seeing what was being run, if at all.

**Comment by justinwalker4179** [comment]
Having one more issue after commenting out the other lines.
```
Traceback (most recent call last):
  File "c:\Users\Iron_Penguin\Documents\Bloc\apprenticeship\honeybot\honeybot\honeybot\main.py", line 13, in <module>
    class Bot_core(object):
  File "c:\Users\Iron_Penguin\Documents\Bloc\apprenticeship\honeybot\honeybot\honeybot\main.py", line 15, in Bot_core
    server_url=config['INFO']['server_url'],
  File "C:\Users\Iron_Penguin\AppData\Local\Programs\Python\Python35-32\lib\configparser.py", line 956, in __getitem__
    raise KeyError(key)
KeyError: 'INFO'
```

**Comment by Abdur-rahmaanJ** [comment]
@justinwalker4179 you need python 3.7

**Comment by Abdur-rahmaanJ** [comment]
also do you have a config file?

**Comment by justinwalker4179** [comment]
Have correct python version, CONNECT. conf has
```
server_url = chat.freenode.net
port = 6667
name = hb_tst00
```

**Comment by Abdur-rahmaanJ** [comment]
@justinwalker4179 try now after tanfry's PR

**Comment by justinwalker4179** [comment]
Tried again with updated version with same error. Do I need to fill in info other than the default for config?

**Comment by TannerFry** [comment]
wait for your config file, do you have this:

[INFO]

server_url = chat.freenode.net
port = 6667
name = hb_tst00

I noticed above, you were missing the [info] part?

**Comment by justinwalker4179** [comment]
Alright, python issued solved. I have python 3.7, and uninstalled all other version a while back, but my ide defaulted to an older version that wasn't supposed to exist for some reason. Ran main, everything seemed to be running normally.  It received a ping from freenode.net, paused and then ran an infinite loop saying
```
woops string index out of range
'NoneType' object is not subscriptable
Empty line.
```
I commented out those print messages that were causing problems just in case

**Comment by Macr0Nerd** [comment]
This is an issue we’re working on solving. For some reason the program doesn’t properly `pong` back and it’s been like that for a bit.

**Comment by justinwalker4179** [comment]
What's the best way to test out a plugin since I can't get it running?

**Comment by Macr0Nerd** [comment]
No real clue for that one. I’d say move the main code to another file separate from the Plugin class and test it there.

**Comment by justinwalker4179** [comment]
Already wrote the game separately, but I need tpo know what kind of inputs I'll be getting. For example will the user type
```
.hangman("guess")
.hangman "guess"
.hangman.letter("o")
.hangman.restart()
```
If you could give me examples I could finish it up.

**Comment by Macr0Nerd** [comment]
Look at the other plugins. The user will send something like 

.hangman guess a
.hangman restart

**Comment by justinwalker4179** [comment]
This can now be closed
