### ISSUE TITLE
add google search plugin

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/honeybot#27]
requires some thinking. top tip: see if you can find such functionality in other bots!

**Comment by iamnishant14** [comment]
what should the google search return? 
Is it supposed to return the URL or the content of them.

**Comment by Abdur-rahmaanJ** [comment]
content. find a way not to use API key or just switch to another search engine.

but returning a bunch of links also seems useful. you decide!

**Comment by iamnishant14** [comment]
Okay. Picking this up.
