### ISSUE TITLE
add password generator plugin

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/honeybot#29]

**Comment by iamnishant14** [comment]
I'm picking this up

**Comment by Abdur-rahmaanJ** [comment]
ok

**Comment by iamnishant14** [comment]
Pushed the PR. Review and close the issue, if all good.

**Comment by Abdur-rahmaanJ** [comment]
ok closing, just view comments.

**Comment by Macr0Nerd** [comment]
@iamnishant14 @Abdur-rahmaanJ I did some testing, and it did not seem like the password generation plugin worked in IRC.
