### ISSUE TITLE
add automatic plugins docs that generates plugins_info.md

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/honeybot#34]
all plugins have a docstring at the begining describing the author, plugin and commands. pass over the files, extract these doctrings and join them all in a single file to have a one page info on plugins

**Comment by Macr0Nerd** [comment]
How do you want it formatted? Do you just want all of the mods from main.py to be put into a markdown file, a file made when you run a command, or a markdown file premade with all of the doctrings?

**Comment by Abdur-rahmaanJ** [comment]
add a script that pass over each plugin file and write like

Joke
by x, site.com

Joke is blablabla

it has the following commands:
...

**Comment by Abdur-rahmaanJ** [comment]
just a simple script suffices. convert the plugin to a script and add it one folder above @Macr0Nerd

**Comment by Macr0Nerd** [comment]
@Abdur-rahmaanJ the script is currently just that. I'm working on putting it one directory above because for some reason it doesn't want to import everything but it should be done by tonight.

**Comment by Macr0Nerd** [comment]
@Abdur-rahmaanJ i think we should close this issue

**Comment by Abdur-rahmaanJ** [comment]
done
