### ISSUE TITLE
how to cope with external dependencies in plugins?

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/honeybot#38]
for example the dictionary plugin uses an external lib. how do we cope with that scenario? we put all in requirements.txt but then, you don't need it to run the bot. discuss.

**Comment by Macr0Nerd** [comment]
It seems that the easiest way would be to write a [setup](https://docs.python.org/3/distutils/setupscript.html) script. It would make this a bit easier. Seems like the only real viable option. @Abdur-rahmaanJ

**Comment by Abdur-rahmaanJ** [comment]
@Macr0Nerd we can add a requirements.txt i mean the bot does not need it, only plugins, maybe a configuration script. we can also add a depemdency section in file docstring. let us see what other plugin contributers like @kylegalloway @iamnishant14 @ajimenezUCLA @sseryani @German-Corpaz @colbyjayallen

**Comment by Macr0Nerd** [comment]
@Abdur-rahmaanJ I'm closing this as we've satiated the requirement.txt
