### ISSUE TITLE
plugin greet everyone who joins the channel 

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/honeybot#43]
beware just don't greet everyone who just sends messages. needs to detect joining event

**Comment by Alecg956** [comment]
I am looking to make an open source contribution for a graded class.  Do you think that some of the beginner issues listen in this repository would be reasonable to do in around two weeks?  I am open to chatting via another medium if you would be willing to discuss further.

**Comment by Abdur-rahmaanJ** [comment]
@Alecg956 actually fell free, ask any questions, you can do any interesting task you find!

**Comment by Alecg956** [comment]
Hi Abdur, do you have an estimation on how long this task would take?  We are looking to take on a semi-complex task that will take around a week to complete?  There is not much information in this issue report.

**Comment by Abdur-rahmaanJ** [comment]
@Alecg956 actually you have to detect when does someone joins the channel. Retrieve his name and tell: Hi <name>. Yes one week tooo much!

**Comment by Abdur-rahmaanJ** [comment]
@Alecg956 check issue #67

**Comment by Abdur-rahmaanJ** [comment]
you might be interested

**Comment by akshat00** [comment]
Is this open for anyone to do or has someone been assigned

**Comment by Abdur-rahmaanJ** [comment]
try it!

**Comment by RiceAbove** [comment]
I'll try working on this

**Comment by RiceAbove** [comment]
Finished the plugin. Just need approval to merge

**Comment by Abdur-rahmaanJ** [comment]
XD that you can merge. now seeing.
