### ISSUE TITLE
add translation plugin

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/honeybot#46]

**Comment by a-deeb** [comment]
Hi @Abdur-rahmaanJ  ,I would like to help out , in which file do i add the translation plugin?
Also should i refer to to [https://pypi.org/project/googletrans/](https://pypi.org/project/googletrans/) to implement the code

**Comment by Abdur-rahmaanJ** [comment]
@a-deeb thanks!
