### ISSUE TITLE
add mail plugin

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/honeybot#5]

**Comment by TannerFry** [comment]
Abdur-Rahmaan, I emailed you recently about this issue and would like to be assigned this issue to be worked on if possible! I just need more detail about the functionality of the plugin you need.

**Comment by Abdur-rahmaanJ** [comment]
ok!

**Comment by TannerFry** [comment]
I have the email plugin implemented, just need to update the documentation for the plugin then a pull request will be submitted.

**Comment by TannerFry** [comment]
The pull request for this feature has been submitted, and this issue is ready to be closed if approved.

**Comment by Abdur-rahmaanJ** [comment]
@TannerFry closing
