### ISSUE TITLE
[strict-first-timers | afraid of git] update readme to include newly-created plugins

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/honeybot#51]

**Comment by justinwalker4179** [comment]
I submitted a pull request for this issue. I am very new to open source. This is only my second PR ever and the first was just a comment. Thank for having issues like this so newbies like me can get used to the process!

**Comment by Abdur-rahmaanJ** [comment]
@justinwalker4179 glad you liked it!
