### ISSUE TITLE
enhance pluginsInfo script to create a richer markdown doc

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/honeybot#52]
enhance https://github.com/Abdur-rahmaanJ/honeybot/blob/master/honeybot/pluginInfo.py

**Comment by Macr0Nerd** [comment]
Can you give an example of how you want it to be formatted @Abdur-rahmaanJ? This is pretty easy fix all things considered.

**Comment by Abdur-rahmaanJ** [comment]
like add # and remove unknown website where none, where there is, put
netween []()

and things like that.

>

**Comment by Macr0Nerd** [comment]
I’ll get on that in a bit

**Comment by Macr0Nerd** [comment]
@Abdur-rahmaanJ I can't make a pull request for this as it's including the wikipedia search function

**Comment by Abdur-rahmaanJ** [comment]
np PR

>

**Comment by Macr0Nerd** [comment]
also been solved
