### ISSUE TITLE
add logging to file to bot

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/honeybot#67]
write whatever message the bot outputs to files in a log folder. name the file as <date-time>.txt . use the logging module if possible

**Comment by door-bell** [comment]
Hey Abdur, I'm looking to make my first open source contribution! Could I work on this issue? I have experience in python and feel like I could take this one on.

**Comment by Macr0Nerd** [comment]
Hi Tim! Feel free to choose any issue that looks interesting! Just make sure you follow the contribution guidelines stated in the readme and by GitHub!

**Comment by Abdur-rahmaanJ** [comment]
@door-bell basically create a logs folder (check if exists if not create) and where we print to cli, wrtie to file also. see the logging module if possible!

**Comment by Abdur-rahmaanJ** [comment]
@door-bell issue already taken. try another or join us on discord

**Comment by door-bell** [comment]
Okay, I'll look for another issue!
