### ISSUE TITLE
add date plugin

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/honeybot#73]
.date today

returns 

date-month-year

**Comment by RiceAbove** [comment]
I'll try working on this unless someone else is working on it

**Comment by bristoll** [comment]
Is this issue still open? I'd want to try to fix it

**Comment by Abdur-rahmaanJ** [comment]
@bristoll for some reason it does not work, the age plugin. try to test it. you know irc?

**Comment by bristoll** [comment]
@Abdur-rahmaanJ  To be honest I'm not very familiar with IRC but if you let me try I'm very interested. I've took a look at the plugin and it's quite simple, so I think I can do a good job with it. Do you have any document about how to PR a fixed issue just in case I found a solution?

**Comment by Abdur-rahmaanJ** [comment]
@bristoll sorry this issue is open. try to do it. the readme has it all ^^_ find and irc client.

**Comment by bristoll** [comment]
Ok, I'll try, thanks
